#      _   _           _     _____  _             _                    #
#     | \ | |         | |   |  __ \| |           (_)                   #
#     |  \| | _____  _| |_  | |__) | |_   _  __ _ _ _ __  ___          #
#     | . ` |/ _ \ \/ / __| |  ___/| | | | |/ _` | | '_ \/ __|         #
#     | |\  |  __/>  <| |_  | |    | | |_| | (_| | | | | \__ \         #
#     |_| \_|\___/_/\_\\__| |_|    |_|\__,_|\__, |_|_| |_|___/         #
#                                           __/ |                      #
#                                          |___/                       #
#                                                                      #
#                          Servidor de Suporte                         #
#                   https://nextplugins.com.br/discord                 #



features:
  # Tempo para o bonus expirar
  expireTime: 60
  # Ativar/Desativar hologramas
  holograms:
    enable: true
    style:
      - '&e&lTESOURO &7[Level @level]'
      - ''
      - '&b[Clique para abrir]'
  # Mundos em que o sistema irá funcionar
  worlds:
    - 'world'
    - 'mina'
    - 'vip'

messages:
  chest-open:
    - ''
    - '&a&lYAY!&a Você acaba de encontrar um tesouro.'
    - ''
    - '&7Clique com o botão direito nele para abrir'


bonus:
  level-one:
    # Level da recompensa (apenas visual)
    level: 1
    # Chance de encontrar minerando
    chance: 15
    # Blocos em que poderão encontrar este bônus
    materials:
      - 'DIAMOND_BLOCK'
      - 'DIAMOND_ORE'
    # Recompensas
    rewards:
      '1':
        # Chance de quando abrir ser essa recompensa
        chance: 50
        # Comandos a serem executados
        command:
          - 'give @player diamond_pickaxe'
          - 'give @player diamond'
      '2':
        chance: 50
        command:
          - 'give @player obsidian'
  level-two:
    # Level da recompensa (apenas visual)
    level: 2
    # Chance de encontrar minerando
    chance: 7.5
    # Blocos em que poderão encontrar este bônus
    materials:
      - 'GOLD_BLOCK'
      - 'GOLD_ORE'
    # Recompensas
    rewards:
      '1':
        # Chance de quando abrir ser essa recompensa
        chance: 50
        # Comandos a serem executados
        commands:
          - 'give @player gold_ingot'
          - 'give @player diamond'
      '2':
        chance: 50
        commands:
          - 'give @player obsidian'
